# Generated by Django 2.1.7 on 2019-03-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20190315_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='details',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventname',
            new_name='title',
        ),
    ]
